server:
  port: 8080

spring:
  application:
    name: crud
  datasource:
    url: jdbc:postgresql://localhost:5432/user_table
    username: postgres
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

